name: Build and deploy Node.js app to Azure Web App - alto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          # Optionally, you can cache npm dependencies
          cache: 'npm'

      - name: npm install
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Run tests
        run: npx jest --passWithNoTests

      - name: Upload build artifacts for deployment
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact # This is just a label for the artifact
          path: ./build # This is the output directory of your React build command

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'alto'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CE6082F946DD4AC0B191680376A17ECB }}
          package: build # Specify the directory containing your build artifacts, which is the 'build' directory for React apps
